name: C/C++ CI
env:
  Application_Name: "LowOrbitalEarth"
  Application_Version : "Version 0.1"

on:
  push:
    branches: 
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test_step
        run: |
          echo "Hello from LOE 0.1 -${{env.Application_Name}}"
          ls -la
      - name: step2
        uses: actions/checkout@v1
      - name: step3
        run: ls -la
       


