name: C/C++ CI
env:
  Application_Name: "LowOrbitalEarth"
  Application_Version : "Version 0.1"

on:
  push:
    branches: 
      - master
  
jobs:
  build:
     runs-on: ubuntu-latest 
     steps:
       - name: Clone_Repository
         uses: actions/checkout@v1
       - name: Step2
         run: |
           ls -la
           gcc --version
           python --version
         
